// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Risk_n_Reward.Web.Data;

#nullable disable

namespace Risk_n_Reward.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Risk_n_Reward.Web.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastActiveDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$DevelopmentHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                            PublicId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Role = "SuperAdmin",
                            UserName = "DevAdmin"
                        });
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Baccarat is a simple card game. You have two option to bet on Player or Banker. The aim is to get as close to nine (9) as possible.",
                            IsEnabled = true,
                            Name = "Baccarat"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An iconic game, get closer to twenty one (21) than the dealer without going over. Everytime you hit or stand matters. Easy enough right?",
                            IsEnabled = true,
                            Name = "BlackJack"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Simple is an understatement. Coin Toss requires the player to call head or tails watch the coin fly and find out if you made the right call. No complex strategy needed it just 50-50 chance.",
                            IsEnabled = true,
                            Name = "CoinToss"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A multiplier grows from one and you aim to cash out before you crash. Wait longer and the reward grows but wait to long and lose it all. A game all about having courage but also knowing when to walk away.",
                            IsEnabled = true,
                            Name = "Crash"
                        },
                        new
                        {
                            Id = 5,
                            Description = "You are shown a card and you guess whether the next card is higher or lower. Simple right?",
                            IsEnabled = true,
                            Name = "HighLow"
                        },
                        new
                        {
                            Id = 6,
                            Description = "In LuckyDice you wager on the chancee of getting a double from a dice roll(e.g two sixes). Fast, unpredictable and oddly satisfying. Roll the the dice and see.",
                            IsEnabled = true,
                            Name = "LuckyDice"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Select five (5) number or use the quick pick and find out if they match the draw. A lottery styled game played with patience and hope. The odds are low but the pay off is worth it. Pick your number and see if lady luck is on your side.",
                            IsEnabled = true,
                            Name = "PickFive"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A ball is spun around a numbered wheel and you a to bet on the square it will land in. Keep it simple with black, red or chase the greater rewards with specific numbers. No two spins are the same and every round is another chance.",
                            IsEnabled = true,
                            Name = "Roulette"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Place your bet, spin the reel and see what lines up. No complex strategy needed, just set the wager and see what lines up. Each line up of symbols hold different payouts.",
                            IsEnabled = true,
                            Name = "Slots"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A poker game against the house. You and the dealer each get dealt the cards and the best hand wins. All the excitement of poker without having to read the room.",
                            IsEnabled = true,
                            Name = "TexasHoldem"
                        });
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BetType")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Payout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("WinStreakAtPlay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FavouriteGameId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FavouriteGameId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JoinDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastActiveDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$DevelopmentHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                            PublicId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Username = "DevPlayer",
                            WalletBalance = 50000.0m
                        });
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fixed amount of VMali added to the player's wallet on reload.",
                            Key = "ReloadAmount",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1000"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Player can only reload once at or below this amount",
                            Key = "ReloadThreshold",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "100"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Minimum WinStreak to qualify for the first bonus tier",
                            Key = "StreakBonus_Threshold_1",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Minimum WinStreak to qualify for the second bonus tier",
                            Key = "StreakBonus_Threshold_2",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Minimum WinStreak to qualify for the third bonus tier",
                            Key = "StreakBonus_Threshold_3",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Payout multiplier applied at streak tier 1",
                            Key = "StreakBonus_Multiplier_1",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1.25"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Payout multiplier applied at streak tier 2",
                            Key = "StreakBonus_Multiplier_2",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1.50"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Payout multiplier applied at streak tier 3",
                            Key = "StreakBonus_Multiplier_3",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "2.00"
                        });
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.WinStreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("WinStreaks");
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.GameSession", b =>
                {
                    b.HasOne("Risk_n_Reward.Web.Models.Game", "Game")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Risk_n_Reward.Web.Models.Player", "Player")
                        .WithMany("GameSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.Player", b =>
                {
                    b.HasOne("Risk_n_Reward.Web.Models.Game", "FavouriteGame")
                        .WithMany("FavouritedBy")
                        .HasForeignKey("FavouriteGameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FavouriteGame");
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.WalletTransaction", b =>
                {
                    b.HasOne("Risk_n_Reward.Web.Models.Player", "Player")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.WinStreak", b =>
                {
                    b.HasOne("Risk_n_Reward.Web.Models.Game", "Game")
                        .WithMany("WinStreak")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Risk_n_Reward.Web.Models.Player", "Player")
                        .WithMany("WinStreaks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.Game", b =>
                {
                    b.Navigation("FavouritedBy");

                    b.Navigation("GameSessions");

                    b.Navigation("WinStreak");
                });

            modelBuilder.Entity("Risk_n_Reward.Web.Models.Player", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("WalletTransactions");

                    b.Navigation("WinStreaks");
                });
#pragma warning restore 612, 618
        }
    }
}
